### PR TITLE
Fix mobile

### PR DESCRIPTION
**Pull request by abylaw**
Fixes:
https://app.asana.com/0/635939677213594/691664412760140

### CODE REVIEW

**Comment by stevepeak** [comment]
@abylaw https://cl.ly/43423Y1I3l14 

> Below is true for all pages

In mobile: still have the illustration present and (maybe) reduce side or expose only one side.
In desktop: it should be fixed to the sides of the screen and never overlap. This can be done with some `@media min-width` css stuff.

**Comment by abylaw** [comment]
Hey @stevepeak: that seems to be the case for me on mobile chrome/chrome/safari: https://fix-mobile--asyncy-homepage.netlify.com/

**Comment by stevepeak** [comment]
I don't think it's working... https://cl.ly/2G1W3s240c01

**Comment by stevepeak** [comment]
Ok, working now. Maybe it was assets that were cached... About 975px and less they disappear. Can we make them hang around more? Maybe just one side at <950.

**Comment by abylaw** [comment]
@stevepeak Have a look now. Let me know what you think.

**Comment by stevepeak** [comment]
Looking better 👍 -- Is this to busy?:: https://cl.ly/3X090x3o0p35

**Pull request merged**
